global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kia-backend'
    metrics_path: '/actuator/prometheus'
    scheme: https
    static_configs:
      - targets:
          - 'backend-service-332406590258.europe-central2.run.app'
